spring:
 data:
  mongodb:
   # MongoDB URI connection string when running in Docker or localhost
   #uri: mongodb://test:test@localhost:27017/chat_app?authSource=admin&authMechanism=SCRAM-SHA-1
   # Optional options for MongoDB database connection
   host: localhost # MongoDB host
   port: 27017 # Default MongoDB port
   database: chat_app # MongoDB database name
   #username: # Username for authentication
   #password: # Password for authentication
   authentication-database: admin # Database used for authentication (default is 'admin')
   # Connection pool settings


server:
 port: 8088


